### ISSUE TITLE
No database rules configuration

### ISSUE THREAD

**Issue by cybercamphackathon** [nosmurf/shk-android#4]
The repository does not specify what is the database rules configuration.
By default, Firebase rule configuration is as follows:

{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}

This is insecure, since it allows any authenticated user (anybody with a Google account) to read and write in the database, including role fields. As a result, anybody with the app could grant admin permissions himself.

Please provide a secure database rules. For example: https://github.com/firebase/firechat/blob/master/rules.json

**Comment by sergiocasero** [comment]
Yes, it is.

We will work hard for improve this security, apologies for that and thanks for remember
